[project]
name = "fabrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arthur Burkham", email = "unincarty@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "highspy>=1.15.1",
    "numpy>=2.5.2",
    "pulp>=3.3.2",
    "pyyaml>=6.0.3",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
